name: LXPlugin
main: io.github.lxgaming.lxplugin.LXPlugin
version: 0.0.2
description: LXPlugin Snapshot
commands:
 Greeting:
  description: Says Hello to the Player.
  usage: /Greeting
 LXRose:
  description: Gives Player Flower From LX_Gaming.
  usage: /LXRose
 ChosenItem:
  description: Gives Player TheChosenOne's Famous Cookie.
  usage: /ChosenItem