name: LXAffection
main: io.github.lxgaming.lxaffection.LXAffection
version: 0.0.1 Snapshot
description: LXAffection Snapshot
commands:
 Heal:
  description: Heals a Player.
  usage: /Heal
 Hug:
  description: Hugs a Player.
  usage: /Hug