name: LXQuest
main: io.github.lxgaming.lxquest.LXQuest
version: 0.0.1
description: LXQuest Snapshot
commands:
 Quest:
  description: Lists all commands for plugin.
  usage: /Quest
 Quest Complete 1:
  description: Complete Quest
  usage: /Quest Complete 1